In [1]:
from google.colab import files
uploaded = files.upload()

Saving iris (1).xlsx to iris (1).xlsx


In [3]:
import pandas as pd

# The uploaded file is an Excel file named 'iris (1).xlsx'
data = pd.read_excel('iris (1).xlsx')
display(data.head())

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [4]:
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Features and target
X = data.drop("species", axis=1)
y = data["species"]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Default model (10 trees)
rf = RandomForestClassifier(n_estimators=10, random_state=42)
rf.fit(X_train, y_train)

# Prediction
y_pred = rf.predict(X_test)

# Results
print("Accuracy (10 trees):", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy (10 trees): 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [5]:
best_score = 0
best_trees = 0

for n in [10, 20, 50, 100, 150, 200]:
    model = RandomForestClassifier(n_estimators=n, random_state=42)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    score = accuracy_score(y_test, pred)
    print(f"Trees: {n}, Accuracy: {score}")

    if score > best_score:
        best_score = score
        best_trees = n

print("\nBest Accuracy:", best_score)
print("Best Trees:", best_trees)

Trees: 10, Accuracy: 1.0
Trees: 20, Accuracy: 1.0
Trees: 50, Accuracy: 1.0
Trees: 100, Accuracy: 1.0
Trees: 150, Accuracy: 1.0
Trees: 200, Accuracy: 1.0

Best Accuracy: 1.0
Best Trees: 10


In [6]:
import numpy as np

results = {
    "Best Accuracy": best_score,
    "Best Trees": best_trees
}

print(results)

{'Best Accuracy': 1.0, 'Best Trees': 10}
